name: Deploy and Import Data

on:
  push:
    branches:
      - main  # Або інша гілка для деплою

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.5'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Import data from backup.sql
        run: |
          psql $DATABASE_URL -f backup.sql
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
