name: Import Data to Render

on:
  push:
    branches:
      - main  # або інша гілка для імпорту даних

jobs:
  import_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PostgreSQL
        uses: shivammathur/setup-postgresql@v2
        with:
          postgresql-version: '14'

      - name: Check psql version
        run: psql --version  # Перевірка наявності psql

      - name: Import data from backup.sql
        run: |
          psql $DATABASE_URL -f ./data/backup.sql  # Шлях до вашого файлу backup.sql
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Використовуємо секрет для з'єднання з базою даних
